project:
  type: website
  output-dir: docs

website:
  title: "DataVizBlog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/eric-seltzer
      - icon: linkedin
        href: https://www.linkedin.com/in/eric-seltzer/
format:
  html:
    theme: superhero
    css: styles.css



